branch-defaults:
  master:
    environment: collab-ui-server-1
environment-defaults:
  collab-ui-server-1:
    branch: null
    repository: null
global:
  application_name: collab-ui-server
  default_ec2_keyname: pajeter
  default_platform: Docker 18.06.1-ce
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
